### ISSUE TITLE
Temperature

### ISSUE THREAD

**Issue by Anthony-76** [atlassistant/pytlas#47]
Hi Julien,

In your demo, when I type "up temperature", the temperature down...

Je risque d'avoir froid rapidement ;)

A bientôt et bon courage 
Anthony (de Sysun)

**Comment by YuukanOO** [comment]
Tout simplement parce que les jeux d'entraînement sont un peu faiblards dans la démo 😁 je vais mettre les sources en ligne pour que les tickets soient ouverts là bas.

Merci !
